name: Wheels

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-linux-wheels: #only linux
    name: Build wheels for Linux (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']  #specify the Python versions to build for

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
        working-directory: main  # Specify the directory where setup.py is located

      - name: Build wheels for manylinux
        #run: python -m cibuildwheel --output-dir .wheels
        run: python setup.py bdist_wheel --parallel
        env:
          CIBW_BUILD: "cp39-*"
          #CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          #CIBW_MANYLINUX_I686_IMAGE: manylinux_i686
          CIBW_SKIP: "*-win32 *-win_amd64 *-macosx_*"
        working-directory: main  # Specify the directory where setup.py is located
        
      - uses: actions/upload-artifact@v3
        with:
          name: linux-wheels-python-${{ matrix.python-version }}
          path: main/dist/*.whl
